version: "3.3"

services:
  localstack:
    image: "localstack/localstack:4.2.0"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME=localhost
      - IMAGE_NAME=localstack/localstack:4.2.0
      - USE_LIGHT_IMAGE=1
      - START_WEB=0
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=error
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  kubemq:
    image: kubemq/kubemq-community:latest
    container_name: kubemq
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50000:50000"
    environment:
      - KUBEMQ_HOST=kubemq
