# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test & Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Test & Lint
      run: |
        docker-compose up -d
        scripts/wait-sns.sh
        scripts/wait-sqs.sh
        scripts/wait-kubemq.sh
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.0
        go mod download
        golangci-lint run -v ./...
        go test -count=1 -race ./...
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
